### PR TITLE
fix: Potential severe skill registration bug

### LINKED ISSUE #18: Potential for overlapping skills
If multiple mods which inject skills are loaded in a different order from before, skill IDs may overlap and break.

### PR DESCRIPTION
**Pull request by RatikKapoor**
Deprecates old `RegisterSkill` method in favour for one that mandates a unique identifier for each skill. Previously, it was possible to skills to be loaded out of order and to be unexpectedly assigned the incorrect identifier. These changes also set up JotunnLib to merge SkillInjector in the near future. Closes #18 

Changelog:
- Deprecated `RegisterSkill(string name, string description, float increaseStep = 1f, Sprite icon = null)`
- Added `SkillConfig` class to store custom skill information
- Added new register and get skill methods to support `SkillConfig` implementations

### CODE REVIEW

File: TestMod/TestMod.cs [hunk 1]
```diff
@@ -8,6 +8,7 @@
 using JotunnLib.Managers;
 using JotunnLib.Utils;
 using TestMod.Prefabs;
+using static JotunnLib.Managers.SkillManager;
```
Comment (raduschirliu) [inline TestMod/TestMod.cs:11]: Did we need the static import here?

Comment (RatikKapoor) [reply TestMod/TestMod.cs:11]: Nice eye, I let VS auto import for me haha, let me fix that.

**Review by raduschirliu — APPROVED** [review]
